### ISSUE TITLE
发现问题

### ISSUE THREAD

**Issue by soooul** [Airsaid/Android-PickerView-Library#1]
Calendar calendar = Calendar.getInstance();
    pvTime.setRange(calendar.get(Calendar.YEAR), calendar.get(Calendar.YEAR)+20);//要在setTime 之前才有效果哦
    pvTime.setTime(new Date());
只要已设置这个，选择框里的字体就变得很大，设置字体大小都没有

**Comment by Airsaid** [comment]
已经修复，请使用最新依赖版本：compile 'com.airsaid.library:pickerview:1.0.1'
